In [422]:
import pandas as pd
import numpy as np

In [423]:
def get_px(data, targets):
    classes = np.unique(targets).tolist()
    l = data.shape[1]

    means = np.array([data[targets == c].mean(axis=0) for c in classes])
    cov_mats = np.array([np.cov(data[targets == c], rowvar=False) for c in classes])

    cov_invs = np.linalg.inv(cov_mats)
    cov_dets = np.linalg.det(cov_mats)

    probs = []
    for mean, cov_inv, cov_det in zip(means, cov_invs, cov_dets):
        diff = data - mean
        first = 1 / (np.pow(2*np.pi, l/2) * np.sqrt(cov_det))
        second = np.exp(-1/2 * np.sum(diff @ cov_inv * diff, axis=1))
        probs.append(first * second)

    return np.array(probs).T

In [424]:
def clasif_bayesiano(df):
    pass

In [425]:
iris = pd.read_csv("https://raw.githubusercontent.com/toneloy/data/master/iris.csv")
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [426]:
classes = iris['species'].unique()
classes

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [427]:
dictionary = {clase: i for i, clase in enumerate(classes.tolist())}
dictionary

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

In [428]:
iris_species_decode = iris.copy()
iris_species_decode['species'] = iris['species'].map(dictionary)
iris_species_decode[:150:10]

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
10            5.4          3.7           1.5          0.2        0
20            5.4          3.4           1.7          0.2        0
30            4.8          3.1           1.6          0.2        0
40            5.0          3.5           1.3          0.3        0
50            7.0          3.2           4.7          1.4        1
60            5.0          2.0           3.5          1.0        1
70            5.9          3.2           4.8          1.8        1
80            5.5          2.4           3.8          1.1        1
90            5.5          2.6           4.4          1.2        1
100           6.3          3.3           6.0          2.5        2
110           6.5          3.2           5.1          2.0        2
120           6.9          3.2           5.7          2.3        2
130           7.4          2.8           6.1          1.9        2
140           6.7          3.1           5.6          2.4        2

In [429]:
targets = np.array(iris_species_decode['species'])
targets

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [430]:
iris_species_without_species_col = iris_species_decode.drop('species', axis=1)
data_columns = iris_species_without_species_col.columns.tolist()
data_columns

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [431]:
data = np.array(iris_species_without_species_col)
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [434]:
probs = get_px(data, targets)
probs[:150:10]

array([[1.39205913e+001, 6.84686636e-025, 4.15048202e-040],
       [6.76965233e+000, 4.03977170e-028, 1.48651044e-043],
       [1.20129082e+000, 2.43504147e-022, 2.57304026e-037],
       [6.42806127e+000, 1.08308515e-017, 4.64682311e-031],
       [7.50449705e+000, 6.86030434e-024, 1.80660414e-039],
       [8.41360665e-091, 2.76811315e-001, 1.21610654e-005],
       [4.83726903e-042, 2.33630346e-001, 1.45219591e-005],
       [2.58280841e-104, 8.24223670e-002, 1.62923054e-001],
       [1.41062819e-050, 2.56791233e+000, 7.67146865e-005],
       [1.49406701e-072, 3.94638279e-001, 7.78587786e-003],
       [1.69414302e-200, 9.05362854e-011, 2.69635336e-002],
       [3.61878832e-127, 3.29268444e-003, 5.40808271e-001],
       [1.57900466e-173, 6.05576377e-007, 1.16795168e+000],
       [1.70582007e-186, 6.31829099e-005, 4.16082389e-001],
       [5.80626703e-175, 7.74014867e-010, 7.42086631e-001]])