In [1]:
import numpy as np
import pandas as pd

In [2]:
def get_px(x, m, s):
    l = x.shape[0]

    cte = (1 / np.power(2*np.pi, l/2))
    probs = []
    for m_, s_ in zip(m, s):
        diff = x - m_
        s_det = np.linalg.det(s_)
        s_inv = np.linalg.inv(s_)
        probs.append((cte * (1 / np.sqrt(s_det))) * (np.exp(-1/2 * diff.T @ s_inv @ diff)))
    return probs

In [4]:
m = np.array([[1, 1], [3, 3]])
m.shape

(2, 2)

In [5]:
s = np.array([
    [[1, 0],
     [0, 1]],
    [[1, 0],
     [0, 1]]
])
s.shape

(2, 2, 2)

In [6]:
x1 = np.array([1.8, 1.8])
# x2 = np.array([[2.2], []])

In [7]:
get_px(x1, m, s)

[np.float64(0.08392119574135894), np.float64(0.0377082239499434)]

In [8]:
iris = pd.read_csv("https://raw.githubusercontent.com/toneloy/data/master/iris.csv")
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [9]:
data = np.array(iris.drop('species', axis=1))
# data = data[:150:10]
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
classes = iris['species'].unique().tolist()
classes

['setosa', 'versicolor', 'virginica']

In [11]:
dictionary = {clase: i for i, clase in enumerate(classes)}
dictionary

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

In [12]:
targets = iris['species'].map(dictionary)
# targets = targets[:150:10]
targets

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [13]:
classes = np.unique(targets)
classes

array([0, 1, 2])

In [14]:
means = np.array([data[targets == c].mean(axis=0) for c in classes])
means

array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])

In [15]:
means.shape

(3, 4)

In [16]:
cov_mats = np.array([np.cov(data[targets == c], rowvar=False) for c in classes])
cov_mats

array([[[0.12424898, 0.09921633, 0.0163551 , 0.01033061],
        [0.09921633, 0.1436898 , 0.01169796, 0.00929796],
        [0.0163551 , 0.01169796, 0.03015918, 0.00606939],
        [0.01033061, 0.00929796, 0.00606939, 0.01110612]],

       [[0.26643265, 0.08518367, 0.18289796, 0.05577959],
        [0.08518367, 0.09846939, 0.08265306, 0.04120408],
        [0.18289796, 0.08265306, 0.22081633, 0.07310204],
        [0.05577959, 0.04120408, 0.07310204, 0.03910612]],

       [[0.40434286, 0.09376327, 0.3032898 , 0.04909388],
        [0.09376327, 0.10400408, 0.07137959, 0.04762857],
        [0.3032898 , 0.07137959, 0.30458776, 0.04882449],
        [0.04909388, 0.04762857, 0.04882449, 0.07543265]]])

In [17]:
cov_mats.shape

(3, 4, 4)

In [18]:
test1 = np.array([4.1, 1.5, 0.4, 0.2])
get_px(test1, means, cov_mats)

[np.float64(4.00013673467648e-14),
 np.float64(5.585813814112382e-19),
 np.float64(9.559091789546744e-38)]

In [19]:
test2 = np.array([5. , 2. , 3.5, 1. ])
get_px(test2, means, cov_mats)

[np.float64(4.8372690273659554e-42),
 np.float64(0.23363034584009457),
 np.float64(1.4521959080203697e-05)]

In [20]:
test3 = np.array([6.7, 3.1, 5.6, 2.4])
get_px(test3, means, cov_mats)

[np.float64(5.8062670337791e-175),
 np.float64(7.740148670215408e-10),
 np.float64(0.7420866308707705)]