In [1]:
import numpy as np

In [2]:
def scatter_matriz_w(x, y):
    classes, counts = np.unique(y, return_counts=True)
    priori = counts / len(y)
    
    sw = np.zeros((x.shape[1], x.shape[1]))
    for i, class_ in enumerate(classes):
        x_class_ = x[y == class_]
        mean_class_ = np.mean(x_class_)

        cov_class_ = np.dot((x_class_ - mean_class_).T, (x_class_ - mean_class_)) / (counts[i] - 1)
        sw += priori[i] * cov_class_
    
    return sw

In [3]:
def scatter_matriz_b(x, y):
    sb = np.zeros((x.shape[1], x.shape[1]))
    global_mean = np.mean(x)

    classes = np.unique(y)
    for class_ in classes:
        x_class_ = x[y == class_]
        mean_class_ = np.mean(x_class_)
        n_class_ = x.shape[0]

        diff = mean_class_ - global_mean
        diff = diff.reshape(-1, 1)
        sb += n_class_ * np.dot(diff.T, diff)
    
    return sb


In [4]:
def scatter_matriz_m(x, y):
    sw = scatter_matriz_w(x, y)
    sb = scatter_matriz_b(x, y)
    return sw + sb

In [5]:
X = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [77, 84, 69],
    [84, 69, 102],
    [96, 102, 113]
])
y = np.array([0, 0, 0, 1, 1, 1])

In [6]:
sw = scatter_matriz_w(X, y)
sw

array([[ 53.2037037 ,  60.42592593,  86.7037037 ],
       [ 60.42592593, 145.89814815,  39.42592593],
       [ 86.7037037 ,  39.42592593, 292.4537037 ]])

In [7]:
np.trace(sw)

np.float64(491.55555555555554)

In [8]:
sb = scatter_matriz_b(X, y)
sb

array([[21902.25925926, 21902.25925926, 21902.25925926],
       [21902.25925926, 21902.25925926, 21902.25925926],
       [21902.25925926, 21902.25925926, 21902.25925926]])

In [9]:
np.trace(sb)

np.float64(65706.77777777777)

In [10]:
sm = scatter_matriz_m(X, y)
sm

array([[21955.46296296, 21962.68518519, 21988.96296296],
       [21962.68518519, 22048.15740741, 21941.68518519],
       [21988.96296296, 21941.68518519, 22194.71296296]])

In [11]:
np.trace(sm)

np.float64(66198.33333333333)