In [2]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [3]:
X = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [77, 84, 69],
    [84, 69, 102],
    [96, 102, 113]
])
y = np.array([0, 0, 0, 1, 1, 1])

In [4]:
gnb = GaussianNB().fit(X, y)
priori = gnb.class_prior_
priori

array([0.5, 0.5])

In [5]:
X_classes = [X[y == c] for c in np.unique(y)]
sw = sum(gnb.class_prior_[i] * np.cov(Xc, rowvar=False) for i, Xc in enumerate(X_classes))
sw

array([[ 46.66666667,  53.25      , 100.41666667],
       [ 53.25      , 137.        ,  55.5       ],
       [100.41666667,  55.5       , 262.66666667]])

In [7]:
mean_global = np.mean(X)
mean_classes = [np.mean(Xc) for Xc in X_classes]

sb = np.zeros((X.shape[1], X.shape[1]))
for i, (mean_c, priori_i) in enumerate(zip(mean_classes, gnb.class_prior_)):
    diff = mean_c - mean_global
    sb += priori_i * np.outer(diff, diff)
sb

array([[1825.1882716, 1825.1882716, 1825.1882716],
       [1825.1882716, 1825.1882716, 1825.1882716],
       [1825.1882716, 1825.1882716, 1825.1882716]])

In [8]:
sm = sw + sb
sm

array([[1871.85493827, 1878.4382716 , 1925.60493827],
       [1878.4382716 , 1962.1882716 , 1880.6882716 ],
       [1925.60493827, 1880.6882716 , 2087.85493827]])

In [9]:
j1 = np.trace(sm) / np.trace(sw)
j1

np.float64(13.267882333416312)

In [12]:
j2 = np.linalg.det(sm) / np.linalg.det(sw)
j2

np.float64(3651.3765432092596)

In [14]:
j3 = np.trace(np.linalg.inv(sw) * sm)
j3

np.float64(25623.674913047045)